
import torch
import math
import torch.nn.functional as F
import torch.nn as nn
import numpy as np
from scipy.spatial.transform import Rotation as R
from typing import Optional

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        lower = norm_cdf((a - mean) / std)
        upper = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [lower, upper], then translate to
        # [2*lower-1, 2*upper-1].
        tensor.uniform_(2 * lower - 1, 2 * upper - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def eef_reconstruction_loss(
    s_pred: torch.Tensor,
    state_delta: Optional[torch.Tensor] = None,
    pos_loss_type: str = "l1",
    reduction: str = "mean",
) -> torch.Tensor:
    """
    只使用预先计算的 state_delta 作为监督信号。
    state 仅用于接口兼容，不参与计算。
    """
    if len(s_pred.shape) == 2:
        s_pred = s_pred.unsqueeze(1)

    if state_delta is None:
        raise ValueError("eef_reconstruction_loss 需要提供 state_delta 作为监督信号。")

    num_steps = s_pred.shape[-2]
    delta = state_delta
    if not torch.is_tensor(delta):
        delta = torch.as_tensor(delta, device=s_pred.device, dtype=s_pred.dtype)
    if delta.dim() == s_pred.dim() - 1:
        delta = delta.unsqueeze(-2)
    if delta.shape[-2] == 1 and num_steps > 1:
        delta = delta.expand(*s_pred.shape[:-2], num_steps, delta.shape[-1])

    if delta.shape[-1] != s_pred.shape[-1]:
        raise ValueError(
            f"state_delta 末尾维度与预测不匹配: delta={delta.shape[-1]}, pred={s_pred.shape[-1]}"
        )

    gripper_dim = max(1, s_pred.shape[-1] - 7) if s_pred.shape[-1] > 7 else 1
    pos_ori_target = delta[..., :-gripper_dim]
    gripper_target = delta[..., -gripper_dim:]

    pos_ori_pred = s_pred[..., :-gripper_dim]
    gripper_pred = s_pred[..., -gripper_dim:]

    if pos_loss_type == "l1":
        pos_ori_loss = torch.abs(pos_ori_pred - pos_ori_target)
    elif pos_loss_type == "l2":
        pos_ori_loss = (pos_ori_pred - pos_ori_target) ** 2
    else:
        raise ValueError(f"Unsupported pos_loss_type: {pos_loss_type}")

    # 抓手默认回归（保持与传入 delta 对齐）
    gripper_loss = torch.abs(gripper_pred - gripper_target)

    total_loss = pos_ori_loss.mean(dim=-1) + 0.1 * gripper_loss.mean(dim=-1)

    if reduction == "mean":
        total_loss = total_loss.mean()
    elif reduction == "sum":
        total_loss = total_loss.sum()
    elif reduction == "none":
        pass
    else:
        raise ValueError(f"Unsupported reduction: {reduction}")

    return total_loss

# Charbonnier loss 定义（避免外部依赖缺失）
def charbonnier_loss(input: torch.Tensor, target: torch.Tensor, eps: float = 0.1) -> torch.Tensor:
    diff = input - target
    return torch.mean(torch.sqrt(diff * diff + eps * eps))



